name: pipeline

on:
  push:
  workflow_dispatch:
jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Analyze with SonarCloud

        # You can pin the exact commit or the version.
        # uses: SonarSource/sonarcloud-github-action@v2.2.0
        uses: SonarSource/sonarcloud-github-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        with:
          # Additional arguments for the SonarScanner CLI
          args:
            # Unique keys of your project and organization. You can find them in SonarCloud > Information (bottom-left menu)
            # mandatory
            -Dsonar.projectKey=devopsfiap_devopsimpacta
            -Dsonar.organization=devopsmbalearning
            # Comma-separated paths to directories containing main source files.
            #-Dsonar.sources= # optional, default is project base directory
            # Comma-separated paths to directories containing test source files.
            #-Dsonar.tests= # optional. For more info about Code Coverage, please refer to https://docs.sonarcloud.io/enriching/test-coverage/overview/
            # Adds more detail to both client and server-side analysis logs, activating DEBUG mode for the scanner, and adding client-side environment variables and system properties to the server-side log of analysis report processing.
            #-Dsonar.verbose= # optional, default is false
          # When you need the analysis to take place in a directory other than the one from which it was launched, default is .
          projectBaseDir: .  
          
  code-analisys:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 21
      uses: actions/setup-java@v6
      with:
        java-version: 21
        distribution: 'temurin'
        
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
        
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.qualitygate.wait=true -Dsonar.projectKey=devopsfiap_devopsimpacta
       
  build: 
    runs-on: ubuntu-latest
    needs: code-analisys
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 21
      uses: actions/setup-java@v6
      with:
        java-version: 21
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: target/
   
    - name: Upload JAR
        #This uploads artifacts from your workflow allowing you to share data between jobs and store data once a workflow is complete.
      uses: actions/upload-artifact@v4.4.0
      with:
        #Set artifact name
        name: artifact
        #From this path
        path: ./target/demo-0.0.2.7-SNAPSHOT.jar
    
    - name: Package
      run: mvn package  
         
  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v6
        with:
          java-version: 21
          distribution: 'temurin'
          package: '*.jar'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

  deploy-azure:
    needs: build  
    name: Deploy-azure
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'    
    environment:
      name: AZURE-PRO        
    steps:
       - name: Download JAR
         uses: actions/download-artifact@v4
         with:
            path: target/  
            
       - name: Display structure of downloaded files
         run: ls -R
         
       - name: DeployAzure   
         uses: azure/webapps-deploy@v2.2.13
         with:
            app-name: FiapAppDVP7
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} 
            package: '${{ github.workspace }}/target/artifact/*.jar'
            clean: false
          
  deploy-STG:
    runs-on: ubuntu-latest
    needs: publish
    
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy 
        shell: bash
        run: |
          echo "Deploy STG"
  
  Smoketest:
    runs-on: ubuntu-latest
    needs: deploy-STG
      
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy 
        shell: bash
        run: |
          sh 'src/main/scripts/smoketest.sh'
  
  testeIntegrados:
    runs-on: ubuntu-latest
    needs: Smoketest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy 
        shell: bash
        run: |
          sh 'src/main/scripts/testeIntegrado.sh'          
          
    
    
